workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60

    integrations:
      app_store_connect: codemagic

    environment:
      groups:
        - my_credentials
      
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.mussy.mussyconnect

      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Asegurar creación de .env en la raíz
        script: |
          echo "Creando el archivo .env de forma explícita..."
          cd /Users/builder/clone
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env
          echo "Contenido actual del directorio:"
          ls -la
          echo "Verificando contenido del archivo .env:"
          cat .env

      - name: Obtener dependencias de Flutter
        script: |
          cd /Users/builder/clone
          flutter pub get

      - name: Instalar CocoaPods
        script: |
          cd /Users/builder/clone/ios
          pod install
          cd ..

      - name: Compilar IPA para TestFlight
        script: |
          cd /Users/builder/clone
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log