workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60

    integrations:
      app_store_connect: codemagic

    environment:
      groups:
        - my_credentials
      
      ios_signing:
        distribution_type: app_store # Configurado para producción y TestFlight
        bundle_identifier: com.mussy.mussyconnect

      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Crear archivo .env de forma segura
        script: |
          echo "Creando archivo .env en la raíz del proyecto..."
          cat << EOF > /Users/builder/clone/.env
          SUPABASE_URL=$SUPABASE_URL
          SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY
          EOF

      - name: Obtener dependencias Flutter
        script: |
          flutter pub get

      - name: Instalar CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Configurar firma de iOS
        script: |
          echo "Configurando certificados y provisioning profiles para App Store..."
          xcode-project use-profiles

      - name: Compilar IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log